spring.application.name=lesson3
spring.jackson.default-property-inclusion=ALWAYS

logging.level.root=INFO
logging.level.org.hse.examples.domain=INFO
logging.level.org.hse.examples.infrastructure=DEBUG